# Site settings
title: Know-AI
subtitle: UH Project.  Funded by Research Council Finland
email: lidia.pivovarova@helsinki.fi
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code:
country: 
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/KNOW-AI-UH
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
